spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/SevvalYuksek/turkcell-config-server
      profile: dev # or prod or anything
server:
  port: 8888